# Generated by Django 3.0.5 on 2020-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
